version: '3'
services:
  client_alpha:
    image: client:latest
    networks:
      - distributed-property-statistics_kafka_network
    environment:
      KAFKA_HOST: "kafka:9093"
      #KAFKA_HOST: "0.0.0.0:9092"
    ports:
      - '8080:8080'
networks:
  distributed-property-statistics_kafka_network:
    external: true
