version: '3.3'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
     - "8000:8000"
    networks:
      - distributed-property-statistics_kafka_network
networks:
  distributed-property-statistics_kafka_network:
    external: true

