version: '3'
services:
  puller_alpha:
    image: puller:latest
    networks:
      - distributed-property-statistics_kafka_network
    environment:
      KAFKA_HOST: "kafka:9093"
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    ports:
      - '8082:8082'
networks:
  distributed-property-statistics_kafka_network:
    external: true
