version: '3'
services:
  puller_alpha:
    image: puller:latest
    networks:
      - distributed-property-statistics_kafka_network
    environment:
      KAFKA_HOST: "kafka:9093"
      #KAFKA_HOST: "0.0.0.0:9092"
    ports:
      - '8082:8082'
networks:
  distributed-property-statistics_kafka_network:
    external: true
